name: Update JSON Files

on:
  schedule:
    # Run this workflow every hour
    - cron: '15 * * * *'

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Japanese JSON file from the website
        run: curl -o getPeople_ja.json https://www.u-tokyo.ac.jp/content/getPeople_ja.json

      - name: Download English JSON file from the website
        run: curl -o getPeople_en.json https://www.u-tokyo.ac.jp/content/getPeople_en.json

      - name: Commit and push if there are changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add getPeople_ja.json
          git add getPeople_en.json
          git commit -m "Hourly update of getPeople JSONs" || exit 0  # No changes error handled
          git push
